# Generated by Django 5.1.3 on 2025-12-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_rename_locked_at_seat_lock_time_alter_seat_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="seats",
            field=models.ManyToManyField(blank=True, to="booking.seat"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
