# Generated by Django 5.1.3 on 2025-12-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_seats_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
