# Generated by Django 5.1.3 on 2026-01-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_booking_quantity_alter_booking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
